# Generated by Django 5.0.6 on 2024-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='car_make_name',
            field=models.CharField(max_length=16),
        ),
    ]
