# Generated by Django 5.0.6 on 2024-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0002_alter_carmake_car_make_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('Бензин', 'Бензин'), ('Газ', 'Газ'), ('Дизель', 'Дизель')], max_length=14, null=True),
        ),
    ]
