# Generated by Django 5.0.6 on 2024-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0004_car_car_name_en_car_car_name_ky_car_car_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_name_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_name_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_name_ru',
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
